remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [SAAD SHAMSI]
description: [Versatile WordPress Developer and DevOps/IT Engineer with 3+ years of experience delivering high-performance websites and secure infrastructure solutions across on‑prem and cloud environments. Skilled in custom WordPress themes, plugins, headless architectures, CI/CD pipelines, containerization (Docker, Kubernetes), and security audits.
Proven track record of boosting conversion rates (+40%), reducing deployment errors (−25%), and conducting 30+ penetration tests. Recognized for rapid incident response, cross-functional collaboration, and building reliable, high-availability systems.
]
